name: flutter_string_scanner
description: A tool to scan Flutter projects for untranslated static strings, helping improve multi-language support.
version: 1.0.1
homepage: https://github.com/0MohamedNagy/flutter_string_scanner
repository: https://github.com/0MohamedNagy/flutter_string_scanner
issue_tracker: https://github.com/0MohamedNagy/flutter_string_scanner/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.3.1

dev_dependencies:
  test: ^1.21.0

